### ISSUE TITLE
Order of blog posts

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#299]
Hello!

The blog posts seem to have come back to a vertical order. Would it be possible to sort them horizontally again? Meaning that the most recent ones will appear on the top of the page (from left to right)?

Many thanks!

**Comment by MobileMaggie** [comment]
The goal is - the blog posts should be sorted (pinned, then
reverse-chronological) horizontally, such that you see all of the most
recent ones at one glance, but the spacing should be a masonry layout -
i.e. not snapped to the grid, but equally spaced between tile + text of
varying sizes due to varying image sizes.

For example:

[image: image.png]

the issue seems to be that we can't have both with this template - can it
be fixed?




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075

**Comment by frasanz** [comment]
Yes, we need to sort in another way, although it's not a priority for second release (v0.5). Moving it to v0.6

**Comment by vvalvesga** [comment]
I put blog posts in a list as we said. I assign @frasanz if you can change the design
