### ISSUE TITLE
Manually type the author's name on a blog post

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#304]
With the newsletter process, we will have to publish several news from the other Citizen science projects. 
they are sometimes written by members of the projects who don't have a connection with our platform, so I don't think that we can always ask them to create an account. 
Would there be a way to feature the author's name even if this person doesn't have an account on our website? by directly typing it?

**Comment by luciestei** [comment]
And maybe add the possibility to have several authors?

**Comment by luciestei** [comment]
And finally, would it be possible to make the "editor" authoring by default? or at least put it at the top of the list?

**Comment by vvalvesga** [comment]
In projects you can introduce a contact without problem. And in resources there are a authors field where you can introduce one or more authors separated by commas if they don't exist in our Database. I close this issue.

**Comment by luciestei** [comment]
Hi, many thanks for this, this is noted! But I was more thinking of the blog posts, I am still not able to add a second author and especially not someone who is not registered. Could this be possible?

**Comment by vvalvesga** [comment]
ok, but I understand in a blog the author is someone registered who writes a post about something. It's unique because you're login with an user and you write these post. But if you want to refer to a person or more people maybe the better choice is write their names in the post's body. It's true it will be seen that you have created it but that happens on all platforms, newspaper articles ....
