### ISSUE TITLE
Final table on resources and training resources

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#313]
@MobileMaggie . Do you have time to provide a table where we can see final fields and vocabulary for training resources and resources (in the same table, to see what we have in common for each of them)

**Comment by MobileMaggie** [comment]
I like the way that Peter did it for the PPSR-Core working group, in a
spreadsheet
<https://docs.google.com/spreadsheets/d/1vIInuzOv0ZZuIRqIGN0XRVfRBk-k1PPIRbJUkyUoDM4/edit?usp=drive_web&ouid=105364624303025797289>
- I think we have to document it this way, instead of my tables in the
metadata g-docs
<https://docs.google.com/document/d/10YzLmpEUr0ckzes131NoWn9C_eGqPatdFx6SC5ypUgM/edit#>....(see
page 10 - the first fields are straight from Resources)

Then we can also show them in parallel.

**Comment by MobileMaggie** [comment]
work in progress going on over here: https://docs.google.com/spreadsheets/d/14pRSlebKmWM5EHpzrWPCn2bvVu6Z4TICQDfm9-yXhwo/edit#gid=507665285

**Comment by frasanz** [comment]
Can we close this @MobileMaggie ?
