### ISSUE TITLE
Double name in the moodle integration

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#488]
The full name is used twice, both in the "first name" field and the "last name" field. So usernames look like "Claudia Müller Claudia Müller". Apparently, when a user changes this manually it doesn't stay from one session to the next (showing double again in the next login).

**Comment by frasanz** [comment]
Yes. In fact it is not a bug but a "workaround" solution to login using
OpenID. We have only one field for name and surname in eu-citizen.science.

The good solution for this is to include the surname as a new field in
eu-citizen.science and send it using openid instead of sending the name
twice

Fran

**Comment by frasanz** [comment]
Done
